"""creating migration directory

Revision ID: 0b786c6b173c
Revises: 
Create Date: 2022-03-05 11:37:22.053286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b786c6b173c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('building_name', sa.String(length=255), nullable=False),
    sa.Column('geo_longitude', sa.Float(), nullable=False),
    sa.Column('geo_latitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('sensor_name', sa.String(length=255), nullable=False),
    sa.Column('sensor_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_reading')
    op.drop_table('building')
    # ### end Alembic commands ###
